version: '2.0'
services:
  web:
    build: .
    ports:
    - "1303:8080"
    links:
    - redis
    volumes:
    - ./uploads:/tmp/uploads
  redis:
    image: mongo
    volumes:
    - ./data:/data/db
